export const CHECK_CURRENT_USER = "CHECK_CURRENT_USER";
export const CURRENT_USER_VALID = "CURRENT_USER_VALID";
export const CURRENT_USER_VOID = "CURRENT_USER_VOID";

export const SIGN_IN_USER_FETCH = "SIGN_IN_USER_FETCH";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_IN_USER_FAIL = "SIGN_IN_USER_FAIL";

export const POST_ENTRY = "POST_ENTRY";
export const POST_ENTRY_SUCCESS = "POST_ENTRY_SUCCESS";
export const POST_ENTRY_FAIL = "POST_ENTRY_FAIL";

export const GET_USER_ENTRIES = "GET_USER_ENTRIES";
export const GET_USER_ENTRIES_SUCCESS = "GET_USER_ENTRIES_SUCCESS";
export const GET_USER_ENTRIES_FAIL = "GET_USER_ENTRIES_FAIL";

export const DELETE_ENTRY = "DELETE_ENTRY";
export const DELETE_ENTRY_SUCCESS = "DELETE_ENTRY_SUCCESS";
export const DELETE_ENTRY_FAIL = "DELETE_ENTRY_FAIL";

export const UPDATE_USER = "UPDATE_CURRENT_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const SEARCH_GIFS = "SEARCH_GIFS";
export const SEARCH_GIFS_SUCCESS = "SEARCH_GIFS_SUCCESS";
export const SEARCH_GIFS_FAIL = "SEARCH_GIFS_FAIL";
export const SELECT_GIF = "SELECT_GIF";

export const GET_RANDOM_EMOJIS = "GET_RANDOM_EMOJIS";
export const TOGGLE_EMOJI = "TOGGLE_EMOJI";
