export const CHECK_CURRENT_USER = "CHECK_CURRENT_USER";
export const CURRENT_USER_VALID = "CURRENT_USER_VALID";
export const CURRENT_USER_VOID = "CURRENT_USER_VOID";

export const SIGN_IN_USER_FETCH = "SIGN_IN_USER_FETCH";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_IN_USER_FAIL = "SIGN_IN_USER_FAIL";

export const POST_RESPONSE = "POST_RESPONSE";
export const POST_RESPONSE_SUCCESS = "POST_RESPONSE_SUCCESS";
export const POST_RESPONSE_FAIL = "POST_RESPONSE_FAIL";

export const GET_USER_RESPONSES = "GET_USER_RESPONSES";
export const GET_USER_RESPONSES_SUCCESS = "GET_USER_RESPONSES_SUCCESS";
export const GET_USER_RESPONSES_FAIL = "GET_USER_RESPONSES_FAIL";

export const DELETE_CURRENT_RESPONSE = "DELETE_CURRENT_RESPONSE";
export const DELETE_CURRENT_RESPONSE_SUCCESS =
  "DELETE_CURRENT_RESPONSE_SUCCESS";
export const DELETE_CURRENT_RESPONSE_FAIL = "DELETE_CURRENT_RESPONSE_FAIL";

export const UPDATE_USER = "UPDATE_CURRENT_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
