export const AUTHENTICATED_ROUTE = 'Authenticated'
export const PROFILE_ROUTE = 'Profile'
export const ENTRY_ROUTE = 'Entry'
export const AUTH_LOADING_ROUTE = 'AuthLoading'
export const WELCOME_ROUTE = 'Welcome'
export const NEW_ENTRY_ROUTE = 'NewEntry'
export const CONFIRM_ENTRY_ROUTE = 'ConfirmEntry'
export const ARCHIVE_ROUTE = 'Archive'
